# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: API - ShareNews

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /auth/signIn:
    # This is a HTTP operation
    post:
      # Describe this verb here. Note: you can use markdown
      description: |
        Realiza a autenticação do usuário na plataforma
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: login
          in: query
          description: Login do usuário
          required: true
          type: string
          format: string
        - 
          name: senha
          in: query
          description: Senha do usuário
          required: true
          type: string
          format: string
      tags:
        - Autenticação
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Usuário autenticado com sucesso
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            $ref: '#/definitions/RespostaLogin'
        400:
          description: Parâmetros inválidos/ausentes na requisição
          schema:
            $ref: '#/definitions/Erro'
            
  /categoriaNoticia:
    get:
      description: |
        Obtém uma lista de objectos do tipo `CategoriaNoticia`
      tags:
        - Categoria de Notícia
      responses:
        200:
          description: Coleção de objetos `CategoriaNoticia`
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            type: array
            items:
              $ref: '#/definitions/CategoriaNoticia'
    post:
      description: |
        Obtém uma lista de objectos do tipo `CategoriaNoticia`
      tags:
        - Categoria de Notícia
      responses:
        200:
          description: Coleção de objetos `CategoriaNoticia`
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            type: array
            items:
              $ref: '#/definitions/CategoriaNoticia'

  /categoriaNoticia/:idCategoriaNoticia:
    get:
      description: |
        Obtém um objeto `CategoriaNoticia`
      parameters:
        # An example parameter that is in query and is required
        -
          name: idCategoriaNoticia
          in: query
          description: Identificador da Categoria de notícia
          required: true
          type: string
          format: string
      tags:
        - Categoria de Notícia
      responses:
        200:
          description: Coleção de objetos `CategoriaNoticia`
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            $ref: '#/definitions/CategoriaNoticia'
definitions:
  
  RespostaLogin:
    type: object
    properties:
      sucesso: 
        type: boolean
      mensagem: 
        type: string
      token:
        type: string
      
  Erro:
    type: object
    properties:
      sucesso: 
        type: boolean
      erro:
        type: string
      mensagem: 
        type: string
        
  CategoriaNoticia:
    type: object
    properties:
      _id:
        type: string
      nome:
        type: string
      descricao:
        type: string

  








  